### PR TITLE
Make it work for iOS 10.2 – change method to TLSv1

### PR DESCRIPTION
**Pull request by srna**

### CODE REVIEW

**Comment by samdmarshall** [comment]
Does this break support for older versions of iOS?

**Comment by srna** [comment]
I tested it on iOS 9.3 and 10.2, both working.

**Comment by samdmarshall** [comment]
Ok, I will want to test with some of the older iOS devices I have, which I won't have access to until sometime next week. Once I confirm with my iOS 3 and 5 devices this looks good to merge. Thanks!

**Comment by samdmarshall** [comment]
Could you please update this against my master branch so that I can test without having to install Xcode?

**Comment by srna** [comment]
Done.

**Comment by samdmarshall** [comment]
OK thanks, i should be able to test this out this week now that I have removed the need to build with Xcode.

**Comment by srna** [comment]
Hey @samdmarshall, any progress on this?

**Comment by samdmarshall** [comment]
Sorry for taking so long with this; i've been able to verify this still works on iOS 3 and 5, so i am going to go ahead and merge it. Thanks!

**Comment by srna** [comment]
Thanks. I was just cleaning up my repos and now I can delete my fork. :)

**Pull request merged**
