### PR TITLE
update to swift 2

### LINKED ISSUE #85: SwiftTest Crash on Xcode 7
I'm trying to run the swift example (Xcode 7), and after doing some minor changes to convert to Swift 2 syntax 

``` swift

import SDMMobileDevice

InitializeSDMMobileDevice();

func getDeviceAtIndex(array: NSArray, index: Int) -> SDMMD_AMDeviceRef {
    let device = array.objectAtIndex(index);
    return device as! SDMMD_AMDeviceRef;
}

var deviceList = SDMMD_AMDCreateDeviceList().takeRetainedValue();

var device = getDeviceAtIndex(deviceList, index: 0);

var result1: sdmmd_return_t = SDMMD_AMDeviceConnect(device);
print(result1);
var result2 = SDMMD_AMDeviceStartSession(device);
print(result2)
var domain = CFStringCreateWithCString(kCFAllocatorDefault, "NULL", 0);
var key = CFStringCreateWithCString(kCFAllocatorDefault, "UniqueDeviceID", 0);
var udid = SDMMD_AMDeviceCopyValue(device, domain, key);
//PrintCFType(udid);
var result3 = SDMMD_AMDeviceStopSession(device);
print(result3);
var result4 = SDMMD_AMDeviceDisconnect(device);
print(result4);
//SDMMD_AMDServiceConnectionGetDevice
```

I get a crash on  `return device as! SDMMD_AMDeviceRef;` everytime. Because it cannot convert from AnyObject to COOpaquePointer (SDMMD_AMDeviceRef).

Do you know a possible solution?

### PR DESCRIPTION
**Pull request by felix-dumit**
Fixes #85 by using `unsafeBitcast`

### CODE REVIEW

**Comment by samdmarshall** [comment]
Thank you for doing this. I just learned there might be a way to get this to work as it was originally implemented using the `as!` for type casting. This would require a change to the main library to get the custom CF types registered with the swift runtime, so when I get to review this PR I will see about making that change to make it work without the `unsafeBitcast()` you had to add to get this to work.

**Comment by felix-dumit** [comment]
Awesome! Thanks a lot for this project.
I saw on the readme that there are plans for a cocoa version, I have the option of starting a project using this library now or wait for a few more months so I'm wondering if the cocoa version is near-future or long future?

**Comment by samdmarshall** [comment]
haha, the cocoa version is probably "never" as I don't see myself having a couple of free months to do work on exclusively this. There has been a cocoa implementation of this done by a third party to wrap the CF interfaces but none of that has been contributed upstream to the project yet (and I don't necessarily expect it to be). Sorry. The readme is drastically out of date and I should probably open an issue to eventually getting around to updating it to reflect the current project state.

**Comment by felix-dumit** [comment]
Ok no problem I understand :)

**Pull request closed without merging**
